### ISSUE TITLE
Port find-font

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#1105]
```c
DEFUN ("find-font", Ffind_font, Sfind_font, 1, 2, 0,
       doc: /* Return a font-entity matching with FONT-SPEC on the current frame.
Optional 2nd argument FRAME, if non-nil, specifies the target frame.  */)
  (Lisp_Object font_spec, Lisp_Object frame)
{
  Lisp_Object val = Flist_fonts (font_spec, frame, make_number (1), Qnil);

  if (CONSP (val))
    val = XCAR (val);
  return val;
}
```

**Comment by Compro-Prasad** [comment]
I want to get into this project. Is the porting cookbook enough to get started?

**Comment by shaleh** [comment]
It should be @Compro-Prasad. If not, let us know what is missing.

**Comment by Compro-Prasad** [comment]
I would first need to port `Flist_fonts`. Right?

**Comment by shaleh** [comment]
You do not _have_ to do so. You can import it from `remacs_sys` and wrap it in an unsafe block. It is just another C function.

You could port `find-font` only. Test it and validate it. Then port `list-fonts`.

BTW, in case it is not explicitly mentioned anywhere, I find the best way to handle the porting process is to leave the C code in place and copy it to the Rust source. I then rename it with "rust_" in front. This turns say `find-font` into `rust-find-font`. Now you can test your work in IELM or other places in Emacs and in ERT tests without breaking anything. Once `find-font` and `rust-find-font` 100% agree you can remove the C code and rename the Rust function.

**Comment by Compro-Prasad** [comment]
So, you mean to say that `remacs_sys` makes C functions and variables available in Rust?

**Comment by shaleh** [comment]
`remacs_sys` is the module exposing them for the Rust portion of the tree. `bindgen` is a Rust tool which reads the C headers and outputs `bindings.rs`. This is a massive file of Rust -> C foreign function interfaces (FFI).  `bindgen` is run whenever you compile. https://github.com/Wilfred/remacs/blob/de43398237c958dcf238ddc36fc7624df5df05ba/rust_src/src/remacs_sys.rs#L31 is where the includes start.

**Comment by shaleh** [comment]
In the C code, `Flist_fonts` is created by the `DEFUN` C macro when `list-fonts` is defined. The same process is done by the `lisp_fn` macro in Rust. At the end of each Rust file with `lisp_fn` calls is an include like this one https://github.com/Wilfred/remacs/blob/de43398237c958dcf238ddc36fc7624df5df05ba/rust_src/src/vectors.rs#L606

That include brings in the `defsubr` calls and helps export C functions marked `no_mangle` as well.

**Comment by shaleh** [comment]
On the C side `DEFUN ("list-fonts"...)` makes a C function `Flist_fonts` and C struct `Slist_fonts`.
Rust is a little different. `lisp_fn` wraps the function that is defined with `pub fn list_fonts(..)` creating a new function that is equivalent to the C `Flist_fonts`. In Rust, we can call either the `list_fonts` function or the C exported `Flist_fonts`. It is our practice to make the Rust function `list_fonts` as close to Rust as possible and therefore use types instead of only `LispObject`. In this way we can chain calls to the functions like we would any other code and not need to constantly transform the `LispObject` unlike the C code where `XFOO(object)` is needed everywhere. Which means `Flist_fonts(..)` likely takes a LispObject and `list_fonts(...)` will use `EmacsInt` or `LispVectorRef`. The wrapping function added by `lisp_fn` takes care of using the `From` trait to transform the arguments from LispObject and the return value back into a LispObject as required by the lisp interpreter.

**Comment by brotzeit** [comment]
#1139
