### ISSUE TITLE
brew installed gnutls is not found

### ISSUE THREAD

**Issue by DaanHoogland** [Wilfred/remacs#155]
on macosx checking out and building head leeds to
```
configure: error: The following required libraries were not found:
     gnutls
Maybe some development libraries/packages are missing?
If you don't want to link with them give
     --with-gnutls=no
as options to configure
```

```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
```
$ brew --version
Homebrew 1.1.10
Homebrew/homebrew-core (git revision c723; last commit 2017-02-22)
```
```
$ uname -a
Darwin tjampoer.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
```
from the ui ```10.11.6 (15G1217)```
```
$ xcode-select --version
xcode-select version 2343.
```
I run remacs with spacemacs on fedora and would really love to see it on my mac as well. no prio though :(

**Comment by DaanHoogland** [comment]
not sure if it can run without tls and if i should allow it to

**Comment by Wilfred** [comment]
If you don't have gnutls, then the build won't support SSL or TLS. This means you won't be able to access HTTPS or log in to email accounts using encryption. If you don't use this, then just build without it?

Alternatively, [this page](https://rmore.net/2011/09/29/how-to-make-emacs-ssl-work-on-mac-os-x/) suggests you could install gnutls from macports, or you can install [gnutls using homebrew](http://brewformulas.org/Gnutl).

**Comment by DaanHoogland** [comment]
@wilfred I do have gnutls installed using brew. That is why I made this issue.

**Comment by efouladi** [comment]
The problem is that the configure script cannot find the path to gnutls library and C header files. One way around it is to define the paths to the required files in corresponding environment variables. In my case the paths were:
 "/usr/local/Cellar/gnutls/3.5.10/lib/" and  "/usr/local/Cellar/gnutls/3.5.10/include/gnutls/"

So it works for me if I run the configure script like this: LIBGNUTLS_LIBS=/usr/local/Cellar/gnutls/3.5.10/lib/ LIBGNUTLS_CFLAGS=/usr/local/Cellar/gnutls/3.5.10/include/gnutls/ ./configure  

If you installed gnutls with homebrew, you can easily ask it to give you the paths using the following command: brew list gnutls

**Comment by DaanHoogland** [comment]
thanks, that worked.
