### ISSUE TITLE
Add lisp functions automatically

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#345]
I wonder if there would be a downside to adding lisp functions inside of the lisp_fn macro instead of appending them manually to rust_init_syms in lib.rs ? It would be really convenient if this would be handled automatically.

**Comment by Wilfred** [comment]
Since functions are added in different places in the C codebase, I assumed there was a reason. I'm not aware of any reason though.

I do like that the code is relatively explicit, and I'm not sure how we'd add a function call inside a macro expansion. There's a verbosity-magic tradeoff, we may not be at the sweet spot yet though.

**Comment by brotzeit** [comment]
If we decide to keep it this way, we should consider to move the functions to the according files like in the c codebase. I don't think there is any value in keeping all lisp functions in one big block in lib.rs or how would you want it to look like after all lisp functions were ported ?

**Comment by Wilfred** [comment]
Agreed, it might be tidier to split them up. I don't feel too strongly either way though.

**Comment by shaleh** [comment]
One argument in favor of moving them into the Rust files and out of lib.rs is porters are just adding to the end of the list. This is losing the connection of editfns v. indent v. .....

With each of us chewing at this little by little moving the parts to the file that owns it should help cut down on merge conflicts too.

**Comment by brotzeit** [comment]
Done in #456 :thumbsup:
