### ISSUE TITLE
Discussion forum/IRC channel?

### ISSUE THREAD

**Issue by moosingin3space** [Wilfred/remacs#36]
GitHub Issues isn't a great platform to discuss major features or ask questions, so it might not be a bad idea to set up another forum/IRC channel for that sort of discussion.

**Comment by Wilfred** [comment]
Agreed something would be useful. I'd prefer something super low maintenance as I'm mostly writing Rust for Remacs at the moment :). I'm not sure about IRC as it's realtime and we have contributors on all sorts of different timezones. Gitter has scrollback I suppose, but no Emacs integration (AFAIK)!

**Comment by moosingin3space** [comment]
@Wilfred https://github.com/jleechpe/erc-gitter allows you to use Gitter in Emacs (it's how Spacemacs recommends you ask for help).

**Comment by shymega** [comment]
IRC can be augmented with logging bots (botbot.me), so it's not really out of the question, IMHO, but others may disagree. We could use Discourse for the forums, and Freenode IRC for the servers..

I'm **not** the biggest fan of Gitter, Slack, etc. They are not well suited to FLOSS projects, and are non-free, which I don't not like (ethical reasons

WDYT?

**Comment by moosingin3space** [comment]
Discourse might be the best option if realtime isn't desirable.

**Comment by shymega** [comment]
Hello,

Nathan Moos <notifications@github.com> writes:

> Discourse might be the best option if realtime isn't desirable.

Agreed. At least Discourse is self-hostable as well, IIRC.

-- 
Best regards,
Dom Rodriguez

"Top-posting causes armed conflicts." ~~ anon, the internet

**Comment by jjrh** [comment]
Funny - came here looking for where the mailing list or IRC channel was. 

As a reader I tend to prefer mailing lists since they allow one to read how ever one likes (web browser archives, emacs, mail client, etc) and as a extension of that allows you to keep track of what you have read.  

I like IRC for off the cuff discussion and quick questions (is X implemented, is it known the build from master is failing? etc) Best way to deal with timezones is to just stay connected 24/7 with screen/tmux or a bouncer like ZNC. Understandably that's not a great solution if you're only in one channel. 

One project I follow uses google groups as a mailing list and it works reasonably well. 

Another uses 'launchpad' https://help.launchpad.net/ListHelp which is so so - issue I have which may be the projects decision is I can't subscribe to it without permission (I mostly want to read it in my mail client or offline - not actually post) They don't have a option to download a mbox or something like say emacs-devel does. 

Just my two cents as someone who would subscribe to mostly follow progress.

**Comment by Wilfred** [comment]
OK, now that Gitter is part of GitLab and will be open sourced, I'm even more inclined to give it a try.

I've created a Gitter room in #167, let's give it a go :).
