### ISSUE TITLE
Port use-global-map and use-local-map

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#570]
```c

DEFUN ("use-global-map", Fuse_global_map, Suse_global_map, 1, 1, 0,
       doc: /* Select KEYMAP as the global keymap.  */)
  (Lisp_Object keymap)
{
  keymap = get_keymap (keymap, 1, 1);
  current_global_map = keymap;

  return Qnil;
}

DEFUN ("use-local-map", Fuse_local_map, Suse_local_map, 1, 1, 0,
       doc: /* Select KEYMAP as the local keymap.
If KEYMAP is nil, that means no local keymap.  */)
  (Lisp_Object keymap)
{
  if (!NILP (keymap))
    keymap = get_keymap (keymap, 1, 1);

  bset_keymap (current_buffer, keymap);

  return Qnil;
}
```

**Comment by accidentalrebel** [comment]
So I've ported the `use-global-map function` and I was wondering if you guys can help me by pointing out if my observations are wrong. This is an effort for me to understand more about the porting process so I can better help out in the future.

First of, here is my ported function:
```rust
/// Select KEYMAP as the global keymap.
#[lisp_fn]
pub fn use_global_map(keymap: LispObject) -> LispObject {
    unsafe {
        let map = get_keymap(keymap.to_raw(), true, true);
        _current_global_map = map;
    }

    LispObject::constant_nil()
}
```
Here are my observations:

- All functions return a LispObject. If there is none, `Qnil` is returned. In the ported Rust function it is `LispObject::constant_nil()`.
- `get_keymap` is still an unported C function, which is why when we pass `keymap` to it, we need to call `to_raw()` on it.
- Anything that gets returned from an unported C function should be converted by calling `from_raw()`, like this `from_raw(returned_example_value)`, so that it can be used by Rust functions.
- Calls to unported C functions needs to be placed in `unsafe blocks`. When the unsafe C function is eventually ported properly, then the `unsafe block` will not be needed anymore.

Thanks in advance. There's a lot to wrap my head around, understanding the code as much as possible would really help unravel the codebase.

**Comment by shaleh** [comment]
First, let me reference this document: https://github.com/Wilfred/remacs/wiki/Porting-cookbook
Since you are coming in fresh you could read that and let us know how to improve it.

Now for your observations.

    All functions return a LispObject. If there is none, Qnil is returned. In the ported Rust function it is    LispObject::constant_nil().

All functions marked with the `lisp_fn` macro return a `LispObject` in Rust. If the function has no real return and just returns `Qnil` you can define the function like this:

    #[lisp_fn]
    pub fn foo(obj: LispObject) -> () {
        // do work with obj
        // no return of any type
    }

If a function returns a clear type such as `bool` or an int you can specify that instead.

    #[lisp_fn]
    pub fn foo(should_error: bool) -> EmacsInt {
        if should_error {
            error!("Something bad");
        }
        5
    }

This is because the function in Rust is not the function called by C or by Lisp. The `lisp_fn` macro defines a wrapper function with a similar name but starting with `F`. So my `foo` in the above examples would be called in C as `Ffoo()`. In Rust, the wrapper function translates any parameters back to `LispObject` and translates any return values into `LispObject`.

    get_keymap is still an unported C function, which is why when we pass keymap to it, we need to call to_raw() on it.
    Anything that gets returned from an unported C function should be converted by calling from_raw(), like this from_raw(returned_example_value), so that it can be used by Rust functions.

A Rust `LispObject` is a wrapper around the C `Lisp_Object`. Note the underscore. The `to_raw()` method returns the underlying `Lisp_Object` to be passed into C. However, there are Rust functions that also take and return `Lisp_Object`. Any function with the `no_mangle` macro for instance. The various versions of `from` for `LispObject` take values and wraps the `Lisp_Object` with the Rust `LispObject`.

As you can see, it is not anything returned from a Rust function. It is `LispObject`s that must be transformed. If your `lisp_fn` function returns a `bool` the wrapper function will do the work to return either `Qnil` or `Qt`.

    Calls to unported C functions needs to be placed in unsafe blocks. When the unsafe C function is eventually ported properly, then the unsafe block will not be needed anymore.

`unsafe` in Rust means just that. The compiler cannot make any promises that the memory is handled in a safe manner. Calling across into C is an `unsafe` action. So is using C allocated memory.

Feel free to either propose PRs or open Issues anywhere our comments and documentation is not clear enough. We try but the code is moving fast and we are deep in it so we sometimes forget what is obvious and what is not.

**Comment by shaleh** [comment]
/// Select KEYMAP as the global keymap.
    #[lisp_fn]
    pub fn use_global_map(keymap: LispObject) -> () {
        unsafe {
            let map = get_keymap(keymap.to_raw(), true, true);
            _current_global_map = map;
        }
    }

Note the comment should have 3 slashes. This triggers the documentation collector.

**Comment by shaleh** [comment]
`accessible-keymaps` would be ported like this:

    /// Find all keymaps accessible via prefix characters from KEYMAP.
    /// Returns a list of elements of the form (KEYS . MAP), where the sequence
    /// KEYS starting from KEYMAP gets you to MAP.  These elements are ordered
    /// so that the KEYS increase in length.  The first element is ([] . KEYMAP).
    /// An optional argument PREFIX, if non-nil, should be a key sequence;
    /// then the value includes only maps for prefixes that start with PREFIX.
    #[lisp_fn(min = "1")]
    pub fn accessible_keymaps(keymap: LispObject, prefix: Option<EmacsInt>) -> LispObject {
        // code
    }

See how the second argument is an `Option` type. That is because `min=1` means this function has optional arguments. You can call it in lisp as `(accessible-keymaps map)` or `(accessible-keymaps map 3)`.

**Comment by accidentalrebel** [comment]
Hey thanks for taking the time to reply!

Your comments are really helpful and easy to understand. Just some clarifications:

- You said if in the function has no real return and returns `Qnil` I shouls just have a return type of `()`. I get this and will do this in the  future. However, I saw in other parts of the codebase where they use `LispObject::constant_nil()` as the return type, is this different or do they just do the same thing?
- You also introduced in your example of using the `Option` type. I think I ported a function previously where I did specify `#[lisp_fn (min = "1")]` but did not specify the second argument to be an option type. Is this still correct or should I change that too?

I actually missed the cookbook. I was using the README in the repo as my guide. Good to know there's a cookbook that has more details. Will give it a check in the future and comment if I have any.

Again thanks for the time!

**Comment by accidentalrebel** [comment]
@db48x I see. The wrapping of the return value makes sense to me now. I still need more experience to fully understand the code in the macro, but I get the concept.

> You could also have specified that it was an Option<bool> or even just bool, since the wrapper function would have converted it correctly either way (obviously a straight bool would be best).

Now that you pointed it out, it does make more sense for the second parameter to be bool. When I made it, i assumed that parameters should always be LispObjects based on the other functions I checked that time. I'll be sure to be mindful of this in the future.

Thank you too for the help!
