### ISSUE TITLE
Use of code conversion tool

### ISSUE THREAD

**Issue by edvorg** [Wilfred/remacs#630]
Hi. Have you considered using some code conversion tool to generate rust sources from C sources.
It won't fully automate the process, but at least it could give it a boost. The flow could be:
1. adjust C code to code conversion tool requirements (e.g. change int to i32, float to f32, etc.)
2. run tool on emacs' code base
3. prettify and refactor output of the code conversion tool

Here are some links that might be helpful:
https://gitlab.com/citrus-rs/citrus#citrus-convert-c-to-rust
https://github.com/jameysharp/corrode
https://jamey.thesharps.us/2016/12/09/how-to-translate-large-c-project-to-rust/

**Comment by shaleh** [comment]
It would give us Rust code. But we have been able to improve on the Emacs code by using types. So for instance, we know in some places that we have a LispSymbol so we no longer need to check types of hit the "else some other type". This kind of work can only be done by reasoning through the code. A bigger help would be in figuring out how to get bindgen working (#486 #488) because then we can access the C code without as many shims.

**Comment by shaleh** [comment]
I believe we can close this now that bindgen is merged. Anyone?

**Comment by edvorg** [comment]
Right, thank you! :+1:
