### ISSUE TITLE
Support for guile as the scripting language

### ISSUE THREAD

**Issue by abhi18av** [Wilfred/remacs#66]
Hii @remacs team.

I am completely awed by this work - thanks for making `emacs` ultra-awesome 😄 

I was wondering if support for `guile` as the scripting language is planned? `GuileEmacs` seems to under development for quite some time now and they've taken care than it can compile most of `elisp` code as it is. Now that `remacs` is in spirit of emacs-extensibility, I think it'd be great if all the effort in Guile can be brought fruition in `remacs`.

I think this would be a huge boost since it'd essentially add support for `lua` , `ecmascript` and `emacslisp` and many other languages as mentioned in the [GNU Guile documentation](https://www.gnu.org/software/guile/manual/guile.html#Supporting-Multiple-Languages)

Let me know about  how can I help regarding `guile` integration 👍 

I'll post the relevant links here

- https://www.gnu.org/software/guile/
- https://www.gnu.org/software/guile/docs/guile-tut/tutorial.html
- https://www.gnu.org/software/guile/manual/guile.html

**Comment by roobie** [comment]
Would this require to replace the elisp bytecode as the compiled format, or could Remacs use both?

**Comment by abhi18av** [comment]
Well, the entire project has been designed around the idea of `guile` being a **drop-in scripting language for `emacs-lisp`** as well as many other GNU projects. From what I know one can already use `guile` as the language in GNU Emacs but it's a matter or inertial.

`guile` already addresses many of the issues of `emacs-lisp`.

**Comment by moosingin3space** [comment]
If I recall correctly this should also allow native multithreading in elisp and should also provide a JIT. I think this is a very good idea, but we'd first need (ideally safe) Guile bindings.

**Comment by roobie** [comment]
Something like [this](https://crates.io/crates/guile)? I haven't tried using it, and the documentation seems a bit thin, but it would be a place to start.

Re the multithreading part:
>Guile supports concurrency essentially via POSIX threads. In Guile-Emacs it is possible to launch any number of threads executing Scheme, but this doesn’t solve the problem that Emacs is full of thread-unsafe data structures and global resources, so programming an Emacs extension using concurrent Scheme code might prove to be full of unexpected roadblocks and pitholes. [...]
-- https://www.emacswiki.org/emacs/GuileEmacs#toc9 

Also, for reference
- https://www.emacswiki.org/emacs/GuileEmacsTodo

**Comment by Wilfred** [comment]
I'm a big fan of the GuileEmacs project, and I certainly believe that the Emacs community benefits from multiple elisp implementations!

However, I don't think that Guile is a good fit for Remacs.

* It adds significant implementation complexity. 

  Working on GuileEmacs requires knowledge of Elisp, C and the Guile dialect of Scheme. If GuileEmacs reaches feature completion, it still requires contributors to know all three languages.

  With Remacs at feature completion, contributors just need to know Rust and Elisp.

* It's harder to contribute to.

  Guile requires copyright assignment, which usually requires mailing a physical form to the USA (depending on the nationality of the contributor). It also requires your employer to sign an IP waiver.

  Patches are sent to a mailing list rather than the PR process with integrated CI that we have on GitHub.

I'm eagerly watching GuileEmacs, and I have a build of it on my system. The team is incredibly talented: Andy Wingo gave [the keynote at an LLVM event](http://llvm.org/devmtg/2016-09/)! I don't think it's compatible with Remacs' goals though.

**Comment by abhi18av** [comment]
@Wilfred I am happy that you didn't discard GuileRemacs without your reasons. But for the second one, isn't this the very same problem faced by **Magnar Sveen** of the `multiple-cursors` and `s.el`fame.

Perhaps, there might be a workaround for second one, for the first one I do agree with you that it's gonna be tough but would you say it'd help `emacs` / `remacs` grow as more in line with modern Emacs.

**Comment by joelmccracken** [comment]
Is maintenance of copywright assignment somehow tied in to the GPL? Could a fork be made of Guile that does *not* requite copywright assignment?

**Comment by abhi18av** [comment]
@Wilfred Apparently `fsf` too has made some efforts towards smoothening the process.

[references to updated `fsf` guidelines](https://github.com/wingo/fibers/issues/5#issuecomment-274814660)

**Comment by abhi18av** [comment]
For future reference.
```
Thanks to the work of Robin Templeton, Guile's Elisp implementation is now fully Emacs-compatible,
     implementing all of Elisp's features and quirks in the same way as the editor we know and love.
```
https://news.ycombinator.com/item?id=13884322

**Comment by gwerbin** [comment]
For what it's worth, having to learn Elisp is actually one of the big turn-offs for me using Emacs. I'd rather use a language I already know -- Vimscript is equally silly and the fact that I know it is more of an historical accident than a reflection on its merit.

**Comment by abhi18av** [comment]
@Wilfred , have your opinion changed about possibly working this into the `remacs` distribution ?

**Comment by shaleh** [comment]
I like the idea of Guile. But it runs 100% cross purpose to this project. Moving to Guile means porting most of the code to Guile's C library instead of Emacs's C. Not to Rust.
